FROM python:3.9-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY ./streamlit_app /app/streamlit_app
COPY ./models /app/model

EXPOSE 8501

CMD ["streamlit", "run", "streamlit_app/main.py", "--server.port=8501", "--server.enableCORS=false"]
