FROM python:3.9-slim

WORKDIR /app

COPY requirements.txt .

RUN apt-get update && apt-get install -y libgomp1
RUN pip install --no-cache-dir -r requirements.txt

COPY ./app /app/app
COPY ./models /app/models
COPY ./scripts /app/scripts 

EXPOSE 10000

CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "10000"]
